// "Misao dana / Thought of the day" for TADEX Hub.
// 366 original, unattributed thoughts: [Bosnian, English]. One per day of the year (1–366),
// chosen by the calendar date in Europe/Sarajevo, so it changes automatically at local midnight.
export const THOUGHTS = [
  ["Nova godina, isti tim, još veći ciljevi.", "New year, same team, even bigger goals."],
  ["Dobar kraj godine počinje dobrim januarom.", "A good end of the year starts with a good January."],
  ["Dobar dan počinje jasnim planom i osmijehom.", "A good day starts with a clear plan and a smile."],
  ["Povjerenje se gradi malim, ispunjenim obećanjima.", "Trust is built on small promises kept."],
  ["Svaki zadovoljan kupac je najbolja reklama.", "Every happy customer is the best advertisement."],
  ["Zajedno stižemo dalje nego što bi iko od nas stigao sam.", "Together we go further than any of us would alone."],
  ["Kvalitet se ne provjerava na kraju, nego se gradi od početka.", "Quality isn't checked at the end; it's built in from the start."],
  ["Jasna poruka danas štedi tri poziva sutra.", "A clear message today saves three calls tomorrow."],
  ["Svaka pošiljka nosi i naše ime.", "Every shipment carries our name too."],
  ["Strpljenje u pregovorima često donosi najbolju cijenu.", "Patience in negotiation often brings the best price."],
  ["Pitanje postavljeno na vrijeme vrijedi više od izvinjenja poslije.", "A question asked in time is worth more than an apology later."],
  ["Mali napredak svaki dan vodi do velikih rezultata.", "Small progress every day leads to big results."],
  ["Dobar dobavljač je partner, a ne samo adresa.", "A good supplier is a partner, not just an address."],
  ["Ono što izmjerimo, to možemo i poboljšati.", "What we measure, we can improve."],
  ["Ljubaznost ništa ne košta, a otvara mnoga vrata.", "Kindness costs nothing and opens many doors."],
  ["Danas je dobar dan da nekome olakšamo posao.", "Today is a good day to make someone's work easier."],
  ["Najbolji tim je onaj u kojem se pomoć traži bez straha.", "The best team is one where asking for help comes without fear."],
  ["Tačnost je oblik poštovanja prema kupcu.", "Accuracy is a form of respect for the customer."],
  ["Svaki kontejner počinje jednim dobrim razgovorom.", "Every container begins with one good conversation."],
  ["Problem uočen rano pola je riješenog problema.", "A problem spotted early is half solved."],
  ["Ne moramo biti savršeni, ali moramo biti pouzdani.", "We don't have to be perfect, but we must be reliable."],
  ["Razdaljina između Yiwua i Sarajeva mjeri se povjerenjem, ne kilometrima.", "The distance between Yiwu and Sarajevo is measured in trust, not kilometres."],
  ["Dobra dokumentacija je tihi heroj svake isporuke.", "Good paperwork is the quiet hero of every delivery."],
  ["Kada slušamo kupca, on nam sam kaže kako da rastemo.", "When we listen to customers, they tell us how to grow."],
  ["Uspjeh je zbir dobro odrađenih običnih dana.", "Success is the sum of ordinary days done well."],
  ["Pohvali kolegu danas; dobra riječ daje snagu cijelom timu.", "Praise a colleague today; a kind word strengthens the whole team."],
  ["Prvo razumij potrebu, pa tek onda traži proizvod.", "First understand the need, then look for the product."],
  ["Rok koji poštujemo vrijedi više od cijene koju obećamo.", "A deadline we keep is worth more than a price we promise."],
  ["Hrabrost je i reći: „Ne znam, ali saznat ću.“", "Courage is also saying: \"I don't know, but I'll find out.\""],
  ["Svaka greška je lekcija ako je podijelimo s timom.", "Every mistake is a lesson if we share it with the team."],
  ["Dobar uzorak govori više od sto fotografija.", "A good sample says more than a hundred photos."],
  ["Red na stolu, red u glavi, red u narudžbama.", "A tidy desk, a clear head, orderly orders."],
  ["Rast dolazi kad izađemo malo izvan zone komfora.", "Growth comes when we step a little outside our comfort zone."],
  ["Iskrenost prema kupcu gradi odnos za cijeli život.", "Honesty with customers builds relationships for life."],
  ["Danas uradi jednu stvar bolje nego jučer.", "Today, do one thing better than yesterday."],
  ["Najbrži put do cilja je dobro dogovoren plan.", "The fastest way to the goal is a well-agreed plan."],
  ["Svaki dan na tržištu je prilika da naučimo nešto novo.", "Every day in the market is a chance to learn something new."],
  ["Pouzdan partner je onaj koji se javi i kad vijesti nisu dobre.", "A reliable partner calls even when the news isn't good."],
  ["Zajednički cilj pretvara grupu ljudi u tim.", "A shared goal turns a group of people into a team."],
  ["Pažnja prema detaljima razlikuje dobro od odličnog.", "Attention to detail separates good from great."],
  ["Dobra cijena je važna, ali dobar odnos traje duže.", "A good price matters, but a good relationship lasts longer."],
  ["Zahvalnost na kraju dana čini sutrašnji dan lakšim.", "Gratitude at the end of the day makes tomorrow easier."],
  ["Kupac ne kupuje samo robu, nego i sigurnost.", "Customers buy not only goods but also peace of mind."],
  ["Odgovor u istom danu pokazuje da nam je stalo.", "A same-day reply shows we care."],
  ["Planiraj kao da ima mnogo vremena, radi kao da ga je malo.", "Plan as if there's plenty of time; work as if there's little."],
  ["Svaki veliki posao počeo je kao mala narudžba.", "Every big deal started as a small order."],
  ["Kad dijelimo znanje, cijeli tim postaje jači.", "When we share knowledge, the whole team grows stronger."],
  ["Jasna specifikacija je pola kvalitetne robe.", "A clear specification is half of quality goods."],
  ["Optimizam je alat, ne samo raspoloženje.", "Optimism is a tool, not just a mood."],
  ["Dobro pitanje vrijedi koliko i dobar odgovor.", "A good question is worth as much as a good answer."],
  ["Ne čekaj savršen trenutak; napravi trenutak dobrim.", "Don't wait for the perfect moment; make the moment good."],
  ["Naša reputacija putuje brže od svakog broda.", "Our reputation travels faster than any ship."],
  ["Svaka provjera kvaliteta je obećanje održano unaprijed.", "Every quality check is a promise kept in advance."],
  ["Timski rad znači da tuđi uspjeh slavimo kao svoj.", "Teamwork means celebrating others' success as our own."],
  ["Kad je put dug, dobra ekipa ga čini kraćim.", "When the road is long, a good crew makes it shorter."],
  ["Upornost pretvara „možda“ u „dogovoreno“.", "Persistence turns \"maybe\" into \"deal\"."],
  ["Mirna glava donosi bolje odluke od brzopletosti.", "A calm mind makes better decisions than haste."],
  ["Svaki kupac zaslužuje da se osjeća kao jedini.", "Every customer deserves to feel like the only one."],
  ["Pametna nabavka počinje dobrim pitanjima.", "Smart sourcing begins with good questions."],
  ["Kad obećamo manje, a isporučimo više, kupac to pamti.", "When we promise less and deliver more, the customer remembers."],
  ["Danas je pravi dan za novu ideju.", "Today is the right day for a new idea."],
  ["Sistem koji radi oslobađa vrijeme za ljude.", "A system that works frees up time for people."],
  ["Mostovi između kultura grade se poštovanjem.", "Bridges between cultures are built with respect."],
  ["Bolje je jednom provjeriti nego dvaput objašnjavati.", "Better to check once than to explain twice."],
  ["Svaki uspješan utovar je djelo mnogih ruku.", "Every successful loading is the work of many hands."],
  ["Energija tima raste kad se svaki glas čuje.", "A team's energy grows when every voice is heard."],
  ["Fleksibilnost je snaga, a ne slabost.", "Flexibility is a strength, not a weakness."],
  ["Kupac koji se vraća najveća je nagrada za naš rad.", "A returning customer is the greatest reward for our work."],
  ["Pregovaraj čvrsto, ali uvijek pošteno.", "Negotiate firmly, but always fairly."],
  ["Dobra organizacija pretvara haos u rutinu.", "Good organisation turns chaos into routine."],
  ["Uči od svakog dobavljača, i od dobrih i od loših.", "Learn from every supplier, the good ones and the bad."],
  ["Nasmijan glas se čuje i preko telefona.", "A smiling voice can be heard even over the phone."],
  ["Lakše je zadržati kupca nego pronaći novog.", "It's easier to keep a customer than to find a new one."],
  ["Svaki dan nosi barem jednu dobru vijest; pronađi je.", "Every day brings at least one piece of good news; find it."],
  ["Kvalitetan proizvod po fer cijeni nikad ne izlazi iz mode.", "A quality product at a fair price never goes out of style."],
  ["Vrijeme uloženo u planiranje vraća se dvostruko.", "Time invested in planning comes back twice over."],
  ["Pomozi kolegi danas; sutra će možda on pomoći tebi.", "Help a colleague today; tomorrow they may help you."],
  ["Jasan dogovor čuva dobro prijateljstvo.", "A clear agreement keeps a good friendship."],
  ["Na sajmu se ne kupuje samo roba, nego i ideje.", "At a trade fair you pick up not only goods but also ideas."],
  ["Kad nešto ne znaš, pitaj; kad nešto znaš, podijeli.", "When you don't know something, ask; when you do, share."],
  ["Svaki izazov je prilika da pokažemo šta znamo.", "Every challenge is a chance to show what we can do."],
  ["Pouzdanost je valuta koja nikad ne gubi vrijednost.", "Reliability is a currency that never loses value."],
  ["Malo humora olakša i najteži radni dan.", "A little humour lightens even the hardest workday."],
  ["Uspješan tim slavi i male pobjede.", "A successful team celebrates small wins too."],
  ["Kupčev problem je naš zadatak, ne smetnja.", "A customer's problem is our task, not a nuisance."],
  ["Brz odgovor je dobar, tačan odgovor je još bolji.", "A fast answer is good; an accurate one is even better."],
  ["Uz dobar tim i prepreke postaju stepenice.", "With a good team, obstacles become steps."],
  ["Danas posadi sjeme posla koji ćeš sutra ubirati.", "Today, plant the seed of business you'll harvest tomorrow."],
  ["Svaki detalj na etiketi je važan nekome na kraju lanca.", "Every detail on a label matters to someone at the end of the chain."],
  ["Dobar posao je onaj u kojem obje strane dobijaju.", "A good deal is one where both sides win."],
  ["Vjeruj procesu, ali provjeravaj rezultate.", "Trust the process, but check the results."],
  ["Ko radi s radošću, radi i s kvalitetom.", "Whoever works with joy works with quality."],
  ["Kad se umoriš, sjeti se zašto si počeo.", "When you get tired, remember why you started."],
  ["Svako jutro je nova prilika za dobar posao.", "Every morning is a new chance for good work."],
  ["Logistika je umjetnost da stvari stignu tamo gdje trebaju, kad trebaju.", "Logistics is the art of getting things where they're needed, when they're needed."],
  ["Poštovanje prema dobavljaču vraća se kroz bolju saradnju.", "Respect for suppliers pays back in better cooperation."],
  ["Nema malih poslova kad se rade s pažnjom.", "No job is small when it's done with care."],
  ["Iskustvo je ono što ostane kad iz svake situacije nešto naučimo.", "Experience is what remains when we learn from every situation."],
  ["Najbolja ideja ne vrijedi mnogo bez dobre izvedbe.", "The best idea isn't worth much without good execution."],
  ["Zajedno pronalazimo rješenja koja niko ne bi vidio sam.", "Together we find solutions nobody would see alone."],
  ["Kupac koji nam vjeruje daje nam najveći kapital.", "A customer who trusts us gives us our greatest capital."],
  ["Svaki novi tržišni trend je poziv da budemo bolji.", "Every new market trend is an invitation to improve."],
  ["Dobro raspoloženje je zarazno; neka počne od tebe.", "A good mood is contagious; let it start with you."],
  ["Precizna ponuda štedi vrijeme i kupcu i nama.", "A precise quote saves time for the customer and for us."],
  ["Ne odustaj nakon prvog „ne“; često je to samo „ne još“.", "Don't give up after the first \"no\"; often it just means \"not yet\"."],
  ["Tim koji uči zajedno raste zajedno.", "A team that learns together grows together."],
  ["Svaka uspješna isporuka je mali praznik.", "Every successful delivery is a small celebration."],
  ["Kvalitet je tiha poruka da nam je stalo.", "Quality is a quiet message that we care."],
  ["Prava roba, u pravo vrijeme, na pravom mjestu – to je naš posao.", "The right goods, at the right time, in the right place – that's our job."],
  ["Dobar plan B daje mir planu A.", "A good plan B gives plan A peace of mind."],
  ["Pohvala u pravom trenutku vrijedi više od nagrade.", "Praise at the right moment is worth more than a reward."],
  ["Kad se trudimo zajedno, i težak dan prođe brže.", "When we make an effort together, even a hard day passes faster."],
  ["Pažljivo pročitan ugovor je najbolja zaštita.", "A carefully read contract is the best protection."],
  ["Svaki razgovor s kupcem je prilika da ga bolje upoznamo.", "Every conversation with a customer is a chance to know them better."],
  ["Kreativnost se rađa kad se ne bojimo pitati: „Zašto ne?“", "Creativity is born when we're not afraid to ask: \"Why not?\""],
  ["Naš rad spaja dva svijeta: Kinu i Balkan.", "Our work connects two worlds: China and the Balkans."],
  ["Dobra komunikacija je pola uspješnog posla.", "Good communication is half of a successful deal."],
  ["Ko dobro sluša, dobro i prodaje.", "Whoever listens well sells well."],
  ["Jednostavno rješenje često je najbolje rješenje.", "The simple solution is often the best one."],
  ["Svaka sedmica je nova prilika za bolje rezultate.", "Every week is a new chance for better results."],
  ["Ponosi se poslom koji radiš; on govori o tebi.", "Take pride in the work you do; it speaks for you."],
  ["Kad svi znaju cilj, put postaje lakši.", "When everyone knows the goal, the road gets easier."],
  ["Isporuka na vrijeme je najljepša poruka kupcu.", "On-time delivery is the nicest message to a customer."],
  ["Dobar dobavljač zaslužuje dobru riječ i fer plaćanje.", "A good supplier deserves a kind word and fair payment."],
  ["Svako „hvala“ čini saradnju toplijom.", "Every \"thank you\" makes cooperation warmer."],
  ["Učimo iz brojeva, ali gradimo s ljudima.", "We learn from numbers, but we build with people."],
  ["Kad je teško, tim je najvažniji.", "When things are hard, the team matters most."],
  ["Dobra priprema je pola pobjede na pregovorima.", "Good preparation is half the win in negotiations."],
  ["Danas napravi korak bliže svom cilju.", "Today, take one step closer to your goal."],
  ["Lojalan kupac se ne kupuje, nego zaslužuje.", "A loyal customer isn't bought; they're earned."],
  ["Najbolja reklama je dobro obavljen posao.", "The best advertising is a job well done."],
  ["Svaka ideja zaslužuje da bude saslušana.", "Every idea deserves to be heard."],
  ["Brzina bez tačnosti samo ubrzava greške.", "Speed without accuracy only speeds up mistakes."],
  ["U svakoj kutiji je i dio našeg truda.", "Every box holds a piece of our effort."],
  ["Dugoročni odnosi vrijede više od brze zarade.", "Long-term relationships are worth more than quick profit."],
  ["Smirenost u krizi daje sigurnost cijelom timu.", "Calm in a crisis gives the whole team confidence."],
  ["Postavi visok standard i drži ga se svaki dan.", "Set a high standard and keep to it every day."],
  ["Kad kupac uspije, uspjeli smo i mi.", "When the customer succeeds, so do we."],
  ["Dobra ekipa je kao dobro složen kontejner: sve je na svom mjestu.", "A good team is like a well-packed container: everything in its place."],
  ["Svaki dan je dobar za učenje nove kineske riječi.", "Every day is a good day to learn a new Chinese word."],
  ["Tačan broj komada je pitanje časti.", "The exact piece count is a matter of honour."],
  ["Znanje o proizvodu je najjači argument u prodaji.", "Product knowledge is the strongest argument in sales."],
  ["Pozitivan stav pretvara probleme u zadatke.", "A positive attitude turns problems into tasks."],
  ["Zajedno dijelimo i teret i radost uspjeha.", "Together we share both the load and the joy of success."],
  ["Svaka uredno složena faktura znači mir za knjigovodstvo.", "Every neatly filed invoice means peace of mind for accounting."],
  ["Inovacija počinje kad poželimo uraditi nešto bolje.", "Innovation begins when we want to do something better."],
  ["Iskren odgovor gradi više povjerenja od savršene prezentacije.", "An honest answer builds more trust than a perfect presentation."],
  ["Kad se tim podržava, nijedan cilj nije predaleko.", "When a team supports each other, no goal is too far."],
  ["Dobri ljudi i dobra roba – formula koja uvijek radi.", "Good people and good goods – a formula that always works."],
  ["Pažljivo pakovanje čuva i robu i ugled.", "Careful packing protects both the goods and the reputation."],
  ["Svaki novi kupac je prijateljstvo u nastajanju.", "Every new customer is a friendship in the making."],
  ["Ne broji sate, nego ono što si u njima uradio.", "Don't count the hours; count what you did in them."],
  ["Kad dijelimo informacije, niko ne radi u mraku.", "When we share information, nobody works in the dark."],
  ["Disciplina danas donosi slobodu sutra.", "Discipline today brings freedom tomorrow."],
  ["Uspjeh voli pripremljene.", "Success loves the prepared."],
  ["Svaka uspješna saradnja počinje međusobnim poštovanjem.", "Every successful partnership begins with mutual respect."],
  ["Fokusiraj se na ono što možeš promijeniti.", "Focus on what you can change."],
  ["Dobar tim zna kad treba ubrzati, a kad zastati.", "A good team knows when to speed up and when to pause."],
  ["Svaki proizvod ima priču; mi joj pišemo sretan kraj.", "Every product has a story; we write its happy ending."],
  ["Mudar trgovac gleda i cijenu i vrijednost.", "A wise trader looks at both price and value."],
  ["Nema pogrešnih pitanja, samo propuštenih prilika.", "There are no wrong questions, only missed opportunities."],
  ["Danas budi razlog nečijeg osmijeha.", "Today, be the reason for someone's smile."],
  ["Kontinuitet je tajna dobrih rezultata.", "Consistency is the secret of good results."],
  ["Kupac pamti kako se osjećao, ne samo šta je kupio.", "Customers remember how they felt, not just what they bought."],
  ["Hrabri planovi trebaju vrijedne ruke.", "Bold plans need hard-working hands."],
  ["Rješenje je često bliže nego što mislimo.", "The solution is often closer than we think."],
  ["Kad radimo pošteno, spavamo mirno.", "When we work honestly, we sleep peacefully."],
  ["Svaka luka je početak nečijeg uspjeha.", "Every port is the start of someone's success."],
  ["Tim je jak koliko i njegova komunikacija.", "A team is as strong as its communication."],
  ["Pažnja i strpljenje su najbolji alati u nabavci.", "Attention and patience are the best tools in sourcing."],
  ["Podijeli uspjeh i on će se umnožiti.", "Share success and it will multiply."],
  ["Dobra odluka danas olakšava deset sutrašnjih.", "One good decision today makes ten tomorrow easier."],
  ["Svaki uzorak je prilika da spriječimo problem.", "Every sample is a chance to prevent a problem."],
  ["Rad s osmijehom je rad s više energije.", "Working with a smile is working with more energy."],
  ["Kupcu ne prodajemo samo proizvod, nego rješenje.", "We don't sell customers just a product, but a solution."],
  ["Napredak nije uvijek brz, ali je uvijek vrijedan.", "Progress isn't always fast, but it's always worth it."],
  ["Povjerenje stečeno godinama čuvamo svakim danom.", "Trust earned over years is protected every day."],
  ["Neka tvoja riječ vrijedi kao potpis.", "Let your word be worth as much as a signature."],
  ["Ko planira put, lakše stiže na cilj.", "Whoever plans the route reaches the goal more easily."],
  ["Dobar tim pretvara ideje u djela.", "A good team turns ideas into action."],
  ["Ne gledaj samo današnju narudžbu, gledaj i sljedeću godinu.", "Don't look only at today's order; look at next year too."],
  ["Mali znak pažnje može otvoriti veliki posao.", "A small gesture of care can open a big deal."],
  ["Svaki dan možemo naučiti nešto što će pomoći kupcu.", "Every day we can learn something that will help a customer."],
  ["Zajednički ručak ponekad riješi više od sastanka.", "A shared lunch sometimes solves more than a meeting."],
  ["Tačne mjere spašavaju cijele kontejnere.", "Accurate measurements save whole containers."],
  ["Kad se pogriješi, važno je brzo i pošteno ispraviti.", "When a mistake happens, what matters is fixing it quickly and honestly."],
  ["Neka danas bude dan bez nepotrebnog odgađanja.", "Let today be a day without needless delays."],
  ["Dobar posao se gradi korak po korak, kutiju po kutiju.", "Good business is built step by step, box by box."],
  ["Ljudi su naša najveća vrijednost.", "People are our greatest asset."],
  ["Svaki kupac ima svoju mjeru; naš posao je da je pogodimo.", "Every customer has their own measure; our job is to get it right."],
  ["Kad timu vjeruješ, lakše prepuštaš zadatke.", "When you trust your team, delegating gets easier."],
  ["Optimista vidi rutu, a ne prepreku.", "An optimist sees the route, not the obstacle."],
  ["Kvalitetna fotografija proizvoda je pola prodaje.", "A quality product photo is half the sale."],
  ["Svaka nova tržišna niša je prilika za hrabre.", "Every new market niche is an opportunity for the bold."],
  ["Proaktivnost je kad problem riješimo prije nego što ga kupac primijeti.", "Being proactive means solving a problem before the customer notices it."],
  ["Dobar odnos s prevoznikom je zlata vrijedan.", "A good relationship with the carrier is worth its weight in gold."],
  ["U timu nema „to nije moj posao“.", "In a team, there's no \"that's not my job\"."],
  ["Uspjeh se ne dešava slučajno, nego planski.", "Success doesn't happen by chance; it happens by design."],
  ["Svaka dobro riješena reklamacija jača povjerenje.", "Every complaint resolved well strengthens trust."],
  ["Jutarnja kafa i jasan plan – savršen početak dana.", "Morning coffee and a clear plan – the perfect start to the day."],
  ["Kad se trud vidi, i kupac ga cijeni.", "When effort shows, customers appreciate it."],
  ["Svako tržište ima svoja pravila; učimo ih s poštovanjem.", "Every market has its own rules; we learn them with respect."],
  ["Vrijednost tima mjeri se time kako se ponaša pod pritiskom.", "A team's worth is measured by how it acts under pressure."],
  ["Dobra ideja može doći od bilo koga; budi otvoren.", "A good idea can come from anyone; stay open."],
  ["Svaki posao zaslužuje naš najbolji trud.", "Every job deserves our best effort."],
  ["Kad kupcu kažemo istinu, gradimo budućnost.", "When we tell customers the truth, we build the future."],
  ["Različitost u timu je naša snaga.", "The variety in our team is our strength."],
  ["Malo reda svaki dan sprječava veliki nered.", "A little order every day prevents a big mess."],
  ["Svaki uspješan projekat počinje pitanjem: „Kako možemo pomoći?“", "Every successful project begins with: \"How can we help?\""],
  ["Dobar pregovarač zna kada treba reći „da“.", "A good negotiator knows when to say \"yes\"."],
  ["Budi strpljiv s ljudima, a zahtjevan kad je riječ o kvalitetu.", "Be patient with people and demanding about quality."],
  ["Iza svake brojke u tabeli stoji nečiji trud.", "Behind every number in a spreadsheet is someone's effort."],
  ["Nove prilike dolaze onima koji su spremni.", "New opportunities come to those who are ready."],
  ["Svaki put od Kine do Bosne je mala avantura sa sretnim krajem.", "Every journey from China to Bosnia is a small adventure with a happy ending."],
  ["Dobro je biti brz, ali je bolje biti pouzdan.", "It's good to be fast, but better to be reliable."],
  ["Kad se tim smije, posao teče.", "When the team laughs, work flows."],
  ["Dobra navika vrijedi više od dobre namjere.", "A good habit is worth more than a good intention."],
  ["Svaki kupac koji nas preporuči otvara nova vrata.", "Every customer who recommends us opens new doors."],
  ["Ne obećavaj ono što ne možeš provjeriti.", "Don't promise what you can't verify."],
  ["Zajedničkim snagama i najveća narudžba postaje izvodljiva.", "With joint effort, even the biggest order becomes doable."],
  ["Svaka pouka iz prošlosti je kapital za budućnost.", "Every lesson from the past is capital for the future."],
  ["Pozitivna riječ u e-mailu mijenja ton cijelog razgovora.", "A positive word in an email changes the tone of the whole conversation."],
  ["Budi partner kakvog bi i sam želio imati.", "Be the partner you would like to have."],
  ["Kvalitet nije trošak, nego investicija.", "Quality isn't a cost; it's an investment."],
  ["Svaki dan donosi priliku da nekoga oduševimo.", "Every day brings a chance to delight someone."],
  ["Dobar tim zna da je „mi“ jače od „ja“.", "A good team knows that \"we\" is stronger than \"I\"."],
  ["Pregledaj, potvrdi, pošalji – i mirno spavaj.", "Review, confirm, send – and sleep soundly."],
  ["Ponekad je najbolja odluka sačekati pravu priliku.", "Sometimes the best decision is to wait for the right opportunity."],
  ["Kupci cijene kada ih se sjetimo i bez povoda.", "Customers appreciate being remembered for no particular reason."],
  ["Učenje je investicija koja uvijek donosi kamatu.", "Learning is an investment that always pays interest."],
  ["Svaki problem ima rješenje; ponekad mu treba samo malo više vremena.", "Every problem has a solution; sometimes it just needs a bit more time."],
  ["Rad u timu je kao veslanje: najbrži smo kad smo usklađeni.", "Teamwork is like rowing: we're fastest when we're in sync."],
  ["Jasni rokovi smanjuju stres svima.", "Clear deadlines reduce stress for everyone."],
  ["Kad poznaješ proizvod, lakše ga i preporučiš.", "When you know a product, it's easier to recommend it."],
  ["Ne boj se velikih ciljeva; podijeli ih na male korake.", "Don't fear big goals; break them into small steps."],
  ["Svaka uredna specifikacija je poklon proizvođaču.", "Every tidy specification is a gift to the manufacturer."],
  ["Dobro raspoložen tim je najbolja vizitkarta firme.", "A cheerful team is the company's best business card."],
  ["Uspjeh se gradi na putu, ne samo na cilju.", "Success is built along the way, not only at the finish."],
  ["Pouzdan rok je najbolji prijatelj kupca.", "A reliable deadline is a customer's best friend."],
  ["Kad pomažemo jedni drugima, posao postaje lakši za sve.", "When we help each other, work gets easier for everyone."],
  ["Svaka nova kategorija proizvoda je nova škola.", "Every new product category is a new school."],
  ["Dobar posao ne mora biti glasan da bi bio primijećen.", "Good work doesn't have to be loud to be noticed."],
  ["Danas završi ono što si jučer započeo.", "Today, finish what you started yesterday."],
  ["Kupac je zadovoljan kad zna šta da očekuje.", "A customer is happy when they know what to expect."],
  ["Trgovina je razmjena robe, ali i povjerenja.", "Trade is an exchange of goods, and of trust."],
  ["Svaki pozitivan komentar kupca je zasluga cijelog tima.", "Every positive customer comment is the whole team's credit."],
  ["Uredan sistem je pola obavljenog posla.", "A tidy system is half the job done."],
  ["Kad su ciljevi jasni, i odluke su lakše.", "When goals are clear, decisions are easier."],
  ["Budi znatiželjan; svaka fabrika krije novu ideju.", "Be curious; every factory hides a new idea."],
  ["Dobar dan je onaj u kojem smo nekome riješili problem.", "A good day is one in which we solved someone's problem."],
  ["Saradnja je kad svako da malo više od očekivanog.", "Cooperation is when everyone gives a little more than expected."],
  ["Brzo reagovanje pretvara problem u priliku.", "A quick response turns a problem into an opportunity."],
  ["Svaka sezona donosi nove trendove i nove šanse.", "Every season brings new trends and new chances."],
  ["Najbolji alat u poslu je dobra volja.", "The best tool in business is goodwill."],
  ["Kad poštujemo vrijeme drugih, i oni poštuju naše.", "When we respect others' time, they respect ours."],
  ["Naš uspjeh se mjeri uspjehom naših kupaca.", "Our success is measured by our customers' success."],
  ["Dobra pitanja dobavljaču štede novac kupcu.", "Good questions to a supplier save the customer money."],
  ["Svaki tim ima heroje koji rade tiho; zahvali im.", "Every team has quiet heroes; thank them."],
  ["Neka tvoj rad bude primjer, a ne izgovor.", "Let your work be an example, not an excuse."],
  ["Svaki put kad nešto pojednostavimo, svi dobijamo.", "Every time we simplify something, everyone wins."],
  ["Dobar ugovor je jasan i onima koji ga nisu pisali.", "A good contract is clear even to those who didn't write it."],
  ["Volja i znanje zajedno pomjeraju granice.", "Will and knowledge together push boundaries."],
  ["Kupca nikad ne ostavljaj bez odgovora.", "Never leave a customer without an answer."],
  ["Svaki dan je prilika da budemo malo hrabriji.", "Every day is a chance to be a little braver."],
  ["Dobra logistika je kad niko ne primijeti koliko je bila zahtjevna.", "Good logistics is when nobody notices how demanding it was."],
  ["Tim u kojem se ljudi poštuju radi s poštovanjem.", "A team whose members respect each other works with respect."],
  ["Ne mjeri samo zaradu, mjeri i zadovoljstvo.", "Don't measure only profit; measure satisfaction too."],
  ["Svaki proizvod koji stigne ispravan je mala pobjeda.", "Every product that arrives intact is a small victory."],
  ["Mir i fokus su najbolji saveznici u gužvi.", "Calm and focus are the best allies when things get busy."],
  ["Kad je cilj zajednički, i uspjeh je zajednički.", "When the goal is shared, so is the success."],
  ["Novi dan, nova narudžba, nova prilika.", "New day, new order, new opportunity."],
  ["Svaka dobra navika tima počinje od jednog člana.", "Every good team habit begins with one member."],
  ["Kupac koji razumije cijenu lakše prepoznaje vrijednost.", "A customer who understands the price more easily sees the value."],
  ["Dobar posao je kad se svi rado sjećaju saradnje.", "Good business is when everyone remembers the cooperation fondly."],
  ["Pažljivo vođena evidencija je najbolja memorija firme.", "Careful records are the company's best memory."],
  ["Strpljenje je ključ, a upornost ruka koja ga okreće.", "Patience is the key, and persistence is the hand that turns it."],
  ["Svaka nova veza na tržištu je investicija u budućnost.", "Every new market connection is an investment in the future."],
  ["Kad je komunikacija jasna, kilometri ne smetaju.", "When communication is clear, kilometres don't matter."],
  ["Ne traži krivca, traži rješenje.", "Don't look for someone to blame; look for a solution."],
  ["Dobar tim zna i da se odmori.", "A good team knows how to rest, too."],
  ["Iza svakog dobrog proizvoda stoji neko ko je postavio pravo pitanje.", "Behind every good product is someone who asked the right question."],
  ["Danas pokušaj nešto uraditi jednostavnije.", "Today, try to do something more simply."],
  ["Uspješan trgovac poznaje i robu i ljude.", "A successful trader knows both the goods and the people."],
  ["Svaki osmijeh kolegi čini kancelariju toplijom.", "Every smile to a colleague makes the office warmer."],
  ["Pravi partner ostaje i kad je posao zahtjevan.", "A true partner stays even when the work is demanding."],
  ["Planiranje je mapa, a trud je gorivo.", "Planning is the map, and effort is the fuel."],
  ["Svaki uspješno zatvoren kontejner je priča o timskom radu.", "Every container successfully closed is a story of teamwork."],
  ["Kad se bojiš greške, provjeri još jednom i kreni.", "When you fear a mistake, check once more and go."],
  ["Odličan servis se pamti duže od niske cijene.", "Excellent service is remembered longer than a low price."],
  ["Svaki dan nosi novu priliku za saradnju.", "Every day brings a new chance to work together."],
  ["Pouzdanost se ne vidi odmah, ali se uvijek osjeti.", "Reliability isn't seen at once, but it's always felt."],
  ["Dijeli zasluge, preuzmi odgovornost.", "Share the credit, take the responsibility."],
  ["Dobar pregled troškova je osnova dobre odluke.", "A good overview of costs is the basis of a good decision."],
  ["Ko ulaže u odnose, nikad ne posluje sam.", "Whoever invests in relationships never does business alone."],
  ["Svaka nova vještina čini tim jačim.", "Every new skill makes the team stronger."],
  ["Kad dan loše počne, neka sljedeći korak bude dobar.", "When the day starts badly, make the next step a good one."],
  ["Dobro informisan kupac je zadovoljan kupac.", "A well-informed customer is a satisfied customer."],
  ["Budi uporan u cilju, a fleksibilan u načinu.", "Be persistent about the goal and flexible about the way."],
  ["Svaki pošteno obavljen posao gradi naše ime.", "Every job done honestly builds our name."],
  ["Dobar tim zna da nema velikog uspjeha bez malih koraka.", "A good team knows there's no big success without small steps."],
  ["Danas je savršen dan da nekome kažeš „bravo“.", "Today is a perfect day to tell someone \"well done\"."],
  ["Svaki put kad poslušamo, naučimo nešto vrijedno.", "Every time we listen, we learn something valuable."],
  ["Jasno označena roba brže prolazi kroz svaki proces.", "Clearly labelled goods move faster through every process."],
  ["Uspjeh dolazi brže kad radimo ono što volimo.", "Success comes faster when we do what we love."],
  ["Dobar odnos s kupcem je kao biljka: treba ga redovno njegovati.", "A good customer relationship is like a plant: it needs regular care."],
  ["Ne odgađaj teški poziv; nakon njega dolazi olakšanje.", "Don't put off the hard call; relief comes right after it."],
  ["Svaka faza posla zaslužuje punu pažnju.", "Every phase of the job deserves full attention."],
  ["Zajedno učimo, zajedno rastemo, zajedno slavimo.", "Together we learn, together we grow, together we celebrate."],
  ["Mudar tim zna šta ne zna, i pita.", "A wise team knows what it doesn't know, and asks."],
  ["Svaki kupac donosi priliku da usavršimo naš proces.", "Every customer brings a chance to perfect our process."],
  ["Rad s jasnim prioritetima je rad bez panike.", "Working with clear priorities is working without panic."],
  ["Najvrednije što razmjenjujemo je povjerenje.", "The most valuable thing we trade is trust."],
  ["Svaka uspješna saradnja je vjetar u leđa za sljedeću.", "Every successful partnership is a tailwind for the next."],
  ["Kad se trudiš, i sreća ti se pridruži.", "When you put in the effort, luck tends to join you."],
  ["Dobra priprema čini nemoguće mogućim.", "Good preparation makes the impossible possible."],
  ["Svaki dan donosi nešto zbog čega vrijedi biti zahvalan.", "Every day brings something worth being grateful for."],
  ["Posao je lakši kad znamo da možemo računati jedni na druge.", "Work is easier when we know we can count on each other."],
  ["Dobar trgovac uvijek misli korak unaprijed.", "A good trader always thinks one step ahead."],
  ["Svako novo saznanje o tržištu podijeli s timom.", "Share every new market insight with the team."],
  ["Tačnost u malim stvarima donosi povjerenje u velikim.", "Accuracy in small things brings trust in big ones."],
  ["Pozitivna energija se prenosi brže od svake pošiljke.", "Positive energy travels faster than any shipment."],
  ["Dobro postavljen cilj je pola puta do uspjeha.", "A well-set goal is halfway to success."],
  ["Kad si u nedoumici, izaberi poštenje.", "When in doubt, choose honesty."],
  ["Dobar tim pretvara ponedjeljak u dobar početak.", "A good team turns Monday into a good beginning."],
  ["Svaki dobro složen paket putuje sigurnije.", "Every well-packed parcel travels more safely."],
  ["Uči od kupaca; oni najbolje znaju šta im treba.", "Learn from customers; they know best what they need."],
  ["Kad se rad i radost spoje, rezultati dolaze sami.", "When work and joy come together, results follow."],
  ["Svaka uspješna sedmica počinje dobrim planom u ponedjeljak.", "Every successful week begins with a good plan on Monday."],
  ["Velikodušnost u dijeljenju znanja čini tim nepobjedivim.", "Generosity in sharing knowledge makes a team unbeatable."],
  ["Ponosni smo na rezultat kad smo do njega došli pošteno.", "We're proud of a result when we've reached it honestly."],
  ["Svaki kontakt u Yiwuu je prozor u novi svijet proizvoda.", "Every contact in Yiwu is a window into a new world of products."],
  ["Kad kupac pita, to je prilika, a ne smetnja.", "When a customer asks, it's an opportunity, not an interruption."],
  ["Svaki naš korak ostavlja trag u nečijem poslu.", "Every step we take leaves a mark on someone's business."],
  ["Organizovan tim radi lakše, a postiže više.", "An organised team works more easily and achieves more."],
  ["Neka danas tvoj rad govori umjesto tebe.", "Let your work speak for you today."],
  ["Svaka pouzdana isporuka gradi most između dva tržišta.", "Every reliable delivery builds a bridge between two markets."],
  ["Dobar posao traži i glavu i srce.", "Good business needs both head and heart."],
  ["Kad pogledaš unazad, vidjet ćeš koliko si već napredovao.", "When you look back, you'll see how far you've come."],
  ["Svaka obećana povratna informacija je obaveza; ispuni je.", "Every promised follow-up is a commitment; keep it."],
  ["Tim koji se raduje uspjehu drugih ima budućnost.", "A team that rejoices in others' success has a future."],
  ["Najbolje rješenje je ono koje radi i sutra.", "The best solution is one that still works tomorrow."],
  ["Svaki dobar dogovor zapiši; pamćenje je kratko, a papir strpljiv.", "Write down every good agreement; memory is short, paper is patient."],
  ["Dobra vijest danas može biti tvoja zasluga.", "Today's good news could be your doing."],
  ["Kupac koji osjeti brigu ostaje vjeran.", "A customer who feels cared for stays loyal."],
  ["Svaki novi početak nosi energiju; iskoristi je.", "Every new beginning carries energy; use it."],
  ["Upornost i ljubaznost zajedno otvaraju i zatvorena vrata.", "Persistence and kindness together open even closed doors."],
  ["Dobar plan transporta štedi i novac i živce.", "A good transport plan saves both money and nerves."],
  ["Svaki član tima nosi dio priče o našem uspjehu.", "Every team member carries part of our success story."],
  ["Završen zadatak vrijedi više od deset započetih.", "One finished task is worth more than ten started ones."],
  ["Kvalitetna roba i iskren odnos – naša najbolja preporuka.", "Quality goods and honest dealings – our best recommendation."],
  ["Svaki izazov u Kini ima rješenje, uz malo kreativnosti.", "Every challenge in China has a solution, with a little creativity."],
  ["Dobar tim i u gužvi nađe vremena za ljubaznost.", "A good team finds time for kindness even when it's busy."],
  ["Danas se fokusiraj na ono što donosi najviše vrijednosti.", "Today, focus on what brings the most value."],
  ["Svaki zadovoljan klijent je nova stepenica našeg rasta.", "Every satisfied client is a new step in our growth."],
  ["Pouzdanost se gradi dosljednošću.", "Reliability is built through consistency."],
  ["Nema prečice do kvaliteta, ali ima pametnog puta.", "There's no shortcut to quality, but there is a smart path."],
  ["Svaki put kad održimo riječ, naše ime postaje jače.", "Every time we keep our word, our name grows stronger."],
  ["Kad svi vuku u istom smjeru, teret postaje lakši.", "When everyone pulls in the same direction, the load gets lighter."],
  ["Dobar posao počinje dobrim pitanjem i završava zadovoljnim kupcem.", "Good business starts with a good question and ends with a happy customer."],
  ["Svaki trud koji danas uložiš, sutra će neko osjetiti.", "Someone will feel tomorrow the effort you put in today."],
  ["Iskustvo cijelog tima je naša najveća prednost.", "The whole team's experience is our biggest advantage."],
  ["Uspjeh nije odredište, nego navika.", "Success isn't a destination; it's a habit."],
  ["Svaka godina donosi nove partnere i nova iskustva.", "Every year brings new partners and new experiences."],
  ["Zahvali se dobavljaču za dobar posao; to se pamti.", "Thank a supplier for good work; it's remembered."],
  ["Osvrni se na godinu s ponosom i gledaj naprijed s radošću.", "Look back on the year with pride and ahead with joy."],
  ["Hvala ti što si dio tima TADEX.", "Thank you for being part of the TADEX team."]
];

/** Day of year (1–366) for `date` as seen in Europe/Sarajevo. */
export function dayOfYear(date = new Date(), timeZone = "Europe/Sarajevo") {
  let y, m, d;
  try {
    const parts = new Intl.DateTimeFormat("en-CA", { timeZone, year: "numeric", month: "numeric", day: "numeric" }).formatToParts(date);
    const get = t => Number(parts.find(p => p.type === t).value);
    y = get("year"); m = get("month"); d = get("day");
  } catch {
    y = date.getFullYear(); m = date.getMonth() + 1; d = date.getDate();
  }
  return Math.round((Date.UTC(y, m - 1, d) - Date.UTC(y, 0, 1)) / 864e5) + 1;
}

/** Today's thought: { bs, en, day }. */
export function thoughtOfTheDay(date = new Date()) {
  const day = dayOfYear(date);
  const [bs, en] = THOUGHTS[(day - 1) % THOUGHTS.length];
  return { bs, en, day };
}
